# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/

# Launch Zen Browser (Flatpak)
bind = Super, W, exec, flatpak run app.zen_browser.zen

# Launch opencode in kitty
bind = Super, Y, exec, kitty opencode

# Launch Steam
bind = Super, X, exec, steam

# Keyboard backlight control
bind = , XF86KbdBrightnessDown, exec, brightnessctl --device='asus::kbd_backlight' set 1-
bind = , XF86KbdBrightnessUp, exec, brightnessctl --device='asus::kbd_backlight' set 1+
