#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

if command -v starship &> /dev/null; then
    eval "$(starship init bash)"
fi
. "$HOME/.cargo/env"
